# Auto-generated by Appr_Comp arcs pass (dc_char.tcl --arcs).
# Delay arcs in ns (NLDM, in_slew=0.02ns, load=3fF, compile).
# None = no timing arc (that input does not affect that output) -> 在 delay max 里跳过该弧.

# 精确 FA/HA —— 填 trainer/arith_das.py 里现在全是 None 的 UFO_MAC_CONSTANT
UFO_MAC_CONSTANT = {
    "FA": {"Tas": 0.49, "Tac": 0.48, "Tbs": 0.5, "Tbc": 0.48, "Tcs": 0.46, "Tcc": 0.45},  # = comp32_e994 (exact 3:2)
    "HA": {"Tas": 0.46, "Tac": 0.43, "Tcs": 0.46, "Tcc": 0.43},  # = comp22_94 (exact 2:2)
}

# 近似 cell 延迟弧（alias -> arcs），供阶段3 类型搜索延迟模型
APX_COMPRESSOR_DELAY = {
    "comp32_exact": {"Tas": 0.49, "Tac": 0.48, "Tbs": 0.5, "Tbc": 0.48, "Tcs": 0.46, "Tcc": 0.45},  # comp32_e994 bias=+0.000
    "comp32_apx_pos_1": {"Tas": 0.47, "Tac": 0.47, "Tbs": 0.47, "Tbc": 0.47, "Tcs": 0.46, "Tcc": 0.45},  # comp32_b994 bias=+0.031
    "comp32_apx_pos_2": {"Tas": 0.45, "Tac": 0.0, "Tbs": 0.46, "Tbc": None, "Tcs": 0.46, "Tcc": None},  # comp32_aa54 bias=+0.078
    "comp32_apx_pos_3": {"Tas": None, "Tac": 0.0, "Tbs": 0.44, "Tbc": None, "Tcs": 0.44, "Tcc": None},  # comp32_fe54 bias=+0.188
    "comp32_apx_neg_1": {"Tas": 0.46, "Tac": 0.47, "Tbs": 0.46, "Tbc": 0.47, "Tcs": 0.46, "Tcc": 0.47},  # comp32_a994 bias=-0.016
    "comp32_apx_neg_2": {"Tas": 0.44, "Tac": None, "Tbs": 0.44, "Tbc": None, "Tcs": None, "Tcc": None},  # comp32_5550 bias=-0.312
    "comp32_apx_neg_3": {"Tas": 0.0, "Tac": None, "Tbs": None, "Tbc": None, "Tcs": None, "Tcc": None},  # comp32_5500 bias=-0.500
    "comp22_exact": {"Tas": 0.46, "Tac": 0.43, "Tcs": 0.46, "Tcc": 0.43},  # comp22_94 bias=+0.000
    "comp22_apx_pos_1": {"Tas": 0.44, "Tac": 0.0, "Tcs": 0.46, "Tcc": None},  # comp22_a4 bias=+0.188
    "comp22_apx_pos_2": {"Tas": None, "Tac": 0.0, "Tcs": 0.0, "Tcc": None},  # comp22_e4 bias=+0.250
    "comp22_apx_neg_1": {"Tas": 0.44, "Tac": None, "Tcs": 0.44, "Tcc": None},  # comp22_54 bias=-0.062
    "comp22_apx_neg_2": {"Tas": 0.0, "Tac": None, "Tcs": None, "Tcc": None},  # comp22_50 bias=-0.250
}
