#!/usr/bin/env python3
"""Generate a compact 4:2 compressor library by composing selected 3:2 cells.

Definition used here:
    inputs  : a, b, c, d, cin  (all same bit weight)
    outputs : sum, carry, cout
    value   : sum + 2*carry + 2*cout

Each 4:2 cell is built functionally as two 3:2 compressors:
    s1, carry = C32_0(a, b, c)
    sum, cout = C32_1(s1, d, cin)

The emitted Verilog is flattened SOP from the composed truth table, so downstream
DC characterization can optimize it as a standalone cell.
"""
import argparse
import itertools
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RTL_DIR = os.path.join(HERE, "rtl")


def sop(lut, patterns, input_names):
    ones = [i for i, bit in enumerate(lut) if bit == 1]
    if not ones:
        return "1'b0"
    if len(ones) == len(lut):
        return "1'b1"
    terms = []
    for i in ones:
        bits = patterns[i]
        terms.append(
            "("
            + " & ".join(name if bit == "1" else f"~{name}" for name, bit in zip(input_names, bits))
            + ")"
        )
    return " | ".join(terms)


def emit_module(name, patterns, sum_lut, carry_lut, cout_lut, comment):
    inputs = ["a", "b", "c", "d", "cin"]
    return (
        f"// {comment}\n"
        f"module {name} (a, b, c, d, cin, sum, carry, cout);\n"
        f"    input  a, b, c, d, cin;\n"
        f"    output sum, carry, cout;\n"
        f"    assign sum   = {sop(sum_lut, patterns, inputs)};\n"
        f"    assign carry = {sop(carry_lut, patterns, inputs)};\n"
        f"    assign cout  = {sop(cout_lut, patterns, inputs)};\n"
        f"endmodule\n\n"
    )


def comp32_eval(cell, x, y, z):
    idx = (x << 2) | (y << 1) | z
    return int(cell["sum_lut"][idx]), int(cell["carry_lut"][idx])


def build_entry(c0_name, c0, c1_name, c1, p_one, zero_eps=1e-12):
    patterns = ["".join(map(str, p)) for p in itertools.product([0, 1], repeat=5)]
    probs = []
    sum_lut, carry_lut, cout_lut = [], [], []
    errors = []
    for pat in patterns:
        a, b, c, d, cin = [int(x) for x in pat]
        prob = 1.0
        for bit, p1 in zip((a, b, c, d, cin), p_one):
            prob *= p1 if bit else (1.0 - p1)
        probs.append(prob)

        s1, carry = comp32_eval(c0, a, b, c)
        s2, cout = comp32_eval(c1, s1, d, cin)
        exact = a + b + c + d + cin
        approx = s2 + 2 * carry + 2 * cout
        errors.append(approx - exact)
        sum_lut.append(s2)
        carry_lut.append(carry)
        cout_lut.append(cout)

    wse = sum(p * e for p, e in zip(probs, errors))
    wae = sum(p * abs(e) for p, e in zip(probs, errors))
    er = sum(p for p, e in zip(probs, errors) if e != 0)
    pos_prob = sum(p for p, e in zip(probs, errors) if e > 0)
    neg_prob = sum(p for p, e in zip(probs, errors) if e < 0)
    maxe = max(abs(e) for e in errors)
    if all(e == 0 for e in errors):
        group = "exact"
    elif wse > zero_eps:
        group = "P"
    elif wse < -zero_eps:
        group = "N"
    else:
        group = "Z"
    name = f"comp42_{c0_name.split('_', 1)[1]}_{c1_name.split('_', 1)[1]}"
    return name, {
        "type": "42",
        "group": group,
        "is_exact": group == "exact",
        "builder": {
            "kind": "pair32",
            "first": c0_name,
            "second": c1_name,
        },
        "patterns": patterns,
        "sum_lut": sum_lut,
        "carry_lut": carry_lut,
        "cout_lut": cout_lut,
        "e": errors,
        "weighted_signed_error": wse,
        "weighted_absolute_error": wae,
        "error_rate": er,
        "max_error": maxe,
        "positive_error_prob": pos_prob,
        "negative_error_prob": neg_prob,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--selected", default=os.path.join(HERE, "selected_compressors.json"))
    ap.add_argument("--library", default=os.path.join(HERE, "library.json"))
    ap.add_argument("--out-json", default=os.path.join(HERE, "cand_42_pair32.json"))
    ap.add_argument("--out-rtl", default=os.path.join(RTL_DIR, "comp42_lib.v"))
    ap.add_argument("--out-manifest", default=os.path.join(RTL_DIR, "manifest42.json"))
    ap.add_argument("--out-library", default=os.path.join(HERE, "library42_pair32_func.json"))
    ap.add_argument("--p-one", type=float, default=0.25)
    args = ap.parse_args()

    selected = json.load(open(args.selected))["selected"]
    lib = json.load(open(args.library))["cells"]
    comp32_aliases = [k for k, v in selected.items() if v["type"] == "32"]
    comp32_modules = [(selected[a]["name"], lib[selected[a]["name"]], a) for a in comp32_aliases]

    os.makedirs(RTL_DIR, exist_ok=True)
    p_one = [args.p_one] * 5
    manifest = {}
    src = "// 4:2 compressor library generated by Appr_Comp/gen_comp42_library.py\n\n"
    for c0_name, c0, a0 in comp32_modules:
        for c1_name, c1, a1 in comp32_modules:
            name, entry = build_entry(c0_name, c0, c1_name, c1, p_one)
            entry["alias_pair"] = [a0, a1]
            comment = (
                f"{name} pair=({a0},{a1}) group={entry['group']} "
                f"bias={entry['weighted_signed_error']:+.4f} "
                f"wae={entry['weighted_absolute_error']:.4f} "
                f"ER={entry['error_rate']:.4f} maxe={entry['max_error']}"
            )
            src += emit_module(
                name,
                entry["patterns"],
                entry["sum_lut"],
                entry["carry_lut"],
                entry["cout_lut"],
                comment,
            )
            manifest[name] = entry

    meta = {
        "source": "selected comp32 pair composition",
        "selected": os.path.abspath(args.selected),
        "library": os.path.abspath(args.library),
        "p_one": p_one,
        "n": len(manifest),
    }
    with open(args.out_json, "w") as f:
        json.dump(
            {
                "meta": meta,
                "candidates": manifest,
            },
            f,
            indent=2,
        )
    with open(args.out_rtl, "w") as f:
        f.write(src)
    with open(args.out_manifest, "w") as f:
        json.dump(manifest, f, indent=2)
    with open(args.out_library, "w") as f:
        lib_meta = dict(meta)
        lib_meta["ppa"] = False
        json.dump({"meta": lib_meta, "cells": manifest}, f, indent=2)

    by_group = {}
    for entry in manifest.values():
        by_group[entry["group"]] = by_group.get(entry["group"], 0) + 1
    print(f"comp42 modules: {len(manifest)}")
    print(f"groups: {by_group}")
    print(f"json -> {args.out_json}")
    print(f"rtl  -> {args.out_rtl}")
    print(f"manifest -> {args.out_manifest}")
    print(f"library(no PPA) -> {args.out_library}")


if __name__ == "__main__":
    main()
