#!/usr/bin/env python3
"""Emit synthesizable Verilog for the reconstructed Sayadi TCSI'23 multipliers.

module MUL(clk, a[15:0], b[15:0], out[30:0])  -- project 统一口径 interface
(8-bit variants use out[15:0] in module MUL8_* for archival, not for the harness.)

Usage: python generate_rtl.py assignment16.json
"""
import json
import sys
from sayadi_common import build_schedule, comp_verilog


def sig_name(sig):
    k = sig[0]
    if k == 'pp':
        return f"pp_{sig[1]}_{sig[2]}"
    if k in ('s', 'c'):
        return f"{k}{sig[1]}_{sig[2]}_{sig[3]}"
    raise ValueError(sig)


def emit(N, fam, assignment, modname="MUL"):
    boxes, final_cols, _ = build_schedule(N, fam)
    ncols = 2 * N - 1
    obits = 31 if N == 16 else 2 * N
    lines = [f"// generated by generate_rtl.py — Sayadi TCSI'23 recon, N={N}, family={fam}",
             f"module {modname}(",
             "    input wire clk,",
             f"    input wire [{N-1}:0] a,",
             f"    input wire [{N-1}:0] b,",
             f"    output wire [{obits-1}:0] out",
             ");"]
    # partial products actually referenced
    used_pp = set()
    for bx in boxes:
        for s in bx.inputs:
            if s[0] == 'pp':
                used_pp.add(s)
    for sigs in final_cols.values():
        for s in sigs:
            if s[0] == 'pp':
                used_pp.add(s)
    for s in sorted(used_pp):
        lines.append(f"    wire {sig_name(s)} = a[{s[1]}] & b[{s[2]}];")
    lines.append("")
    for bx in boxes:
        fam_k = assignment.get((bx.stage, bx.col))
        if bx.searchable:
            assert fam_k is not None, f"unassigned slot {bx.slot}"
            f, k = fam_k
        else:
            f, k = bx.family, bx.k
        ports = [sig_name(s) for s in bx.inputs] + ["1'b0"] * (4 - len(bx.inputs))
        s_expr, c_expr = comp_verilog(f, k, ports)
        sn = sig_name(('s', bx.stage, bx.col, bx.idx))
        cn = sig_name(('c', bx.stage, bx.col, bx.idx))
        lines.append(f"    wire {sn} = {s_expr};  // {f}-{k} s{bx.stage} c{bx.col}")
        lines.append(f"    wire {cn} = {c_expr};")
    lines.append("")
    # final two rows -> adder (RCA semantics; DC propagates the constants)
    width = 2 * N
    rows = [[], []]
    for c in sorted(final_cols):
        sigs = final_cols[c]
        assert len(sigs) <= 2, (c, sigs)
        for r, s in enumerate(sigs):
            rows[r].append((c - 1, sig_name(s)))
    for r in (0, 1):
        bits = dict(rows[r])
        vec = ", ".join(bits.get(i, "1'b0") for i in range(width - 1, -1, -1))
        lines.append(f"    wire [{width-1}:0] row{r} = {{{vec}}};")
    lines.append(f"    wire [{width-1}:0] psum = row0 + row1;")
    lines.append(f"    assign out = psum[{obits-1}:0];")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


if __name__ == '__main__':
    asg_file = sys.argv[1] if len(sys.argv) > 1 else 'assignment16.json'
    with open(asg_file) as f:
        raw = json.load(f)
    import os
    os.makedirs('rtl', exist_ok=True)
    for mul, fam in (('mul1', 'ACFGI'), ('mul2', 'ACFGII')):
        asg = {tuple(int(x) for x in k.split(',')): tuple(v) for k, v in raw[mul].items()}
        v = emit(16, fam, asg, "MUL")
        path = f"rtl/sayadi_{mul}_16.v"
        with open(path, 'w') as f:
            f.write(v)
        print("wrote", path)
